# Generated by Django 3.1.3 on 2021-01-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='main_url',
            new_name='explicit_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
